### ISSUE TITLE
Check and fix notebooks to work with photutils v0.3

### ISSUE THREAD

**Issue by bsipocz** [astropy/photutils-datasets#9]
Someone should go over all of the notebooks here in this repo and make sure they work with the new v0.3 release.

Long term solution would be to set up travis or other CI to do this regularly. 
Maybe @cdeil already has a system to test the notebooks in gammapy?

**Comment by cdeil** [comment]
Yes, we started testing notebooks on travis-ci recently for Gammapy.
You can start reading how it works here:
https://github.com/gammapy/gammapy/blob/master/Makefile#L81

It took some trial and error, in the end we run and maintain the list of notebooks to test like this:
- https://github.com/gammapy/gammapy/blob/master/test_notebooks.py
- https://github.com/gammapy/gammapy-extra/blob/master/notebooks/notebooks.yaml

We chose to use https://github.com/paulgb/runipy
We also looked at https://github.com/paulgb/runipy and didn't see any significant pro or con wrt. runipy, so that would be OK to use as well.

Although, just now I looked at
https://github.com/astropy/astropy-tutorials/blob/master/prepare_deploy.py#L68
and they use `runipy` as well, so probably makes sense to keep using that and building up a small group of people that know how it works and can help each other out if there's problems.

The effort to set up CI for notebooks for any give project is a few hours to a day. Possibly I could be persuaded to do it for projects I'm using, like photutils or astroplan. Let me know.

**Comment by pllim** [comment]
I think this should be done by 1.0 (the stable release) -- cc @larrybradley 

Also see astropy/photutils#1072
